-- Phase 5: artefact schemas (prd.md 10.3, decision 8). Source of truth: packages/schemas/*.json.
-- Regenerate with: node packages/schemas/gen-migration.mjs
insert into baton.artifact_schemas (kind, version, schema) values ('user_story', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/user_story/v1","title":"user_story","type":"object","required":["as_a","i_want","so_that"],"properties":{"title":{"type":"string"},"as_a":{"type":"string","minLength":1},"i_want":{"type":"string","minLength":1},"so_that":{"type":"string","minLength":1},"notes":{"type":"string"},"links":{"type":"array","items":{"type":"string"}}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('task_spec', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/task_spec/v1","title":"task_spec","type":"object","required":["title","summary","requirements","acceptance"],"properties":{"title":{"type":"string","minLength":1},"summary":{"type":"string","minLength":1},"user_story":{"type":"string"},"scope":{"type":"array","items":{"type":"string"}},"requirements":{"type":"array","minItems":1,"items":{"type":"string"}},"fields":{"type":"array","items":{"type":"object","required":["name","type"],"properties":{"name":{"type":"string"},"type":{"type":"string"},"validation":{"type":"string"}}}},"api":{"type":"array","items":{"type":"object","required":["method","path"],"properties":{"method":{"type":"string"},"path":{"type":"string"},"purpose":{"type":"string"}}}},"acceptance":{"type":"array","minItems":1,"items":{"type":"object","required":["given","when","then"],"properties":{"given":{"type":"string"},"when":{"type":"string"},"then":{"type":"string"}}}},"open_questions":{"type":"array","items":{"type":"string"}}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('design_spec', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/design_spec/v1","title":"design_spec","type":"object","required":["screens"],"properties":{"screens":{"type":"array","minItems":1,"items":{"type":"object","required":["name","components"],"properties":{"name":{"type":"string"},"route":{"type":"string"},"layout":{"type":"string"},"components":{"type":"array","items":{"type":"object","required":["name"],"properties":{"name":{"type":"string"},"props":{"type":"object"},"states":{"type":"array","items":{"type":"string"}}}}},"copy":{"type":"object"}}}},"tokens":{"type":"object"},"accessibility":{"type":"array","items":{"type":"string"}},"notes":{"type":"string"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('api_contract', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/api_contract/v1","title":"api_contract","type":"object","required":["endpoints"],"properties":{"base_path":{"type":"string"},"version":{"type":"string"},"auth":{"type":"string"},"endpoints":{"type":"array","minItems":1,"items":{"type":"object","required":["method","path"],"properties":{"method":{"type":"string","enum":["GET","POST","PUT","PATCH","DELETE"]},"path":{"type":"string"},"request":{"type":"object"},"response":{"type":"object"},"errors":{"type":"array"},"purpose":{"type":"string"}}}}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('service_contract', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/service_contract/v1","title":"service_contract","type":"object","required":["service","endpoints"],"properties":{"service":{"type":"string","minLength":1},"endpoints":{"type":"array","minItems":1,"items":{"type":"object","required":["method","path"],"properties":{"method":{"type":"string"},"path":{"type":"string"},"request":{"type":"object"},"response":{"type":"object"}}}},"models":{"type":"array","items":{"type":"object","properties":{"provider":{"type":"string"},"model":{"type":"string"},"purpose":{"type":"string"}}}},"limits":{"type":"object"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('build', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/build/v1","title":"build","type":"object","required":["sha","test_command"],"properties":{"sha":{"type":"string","minLength":1},"branch":{"type":"string"},"repo":{"type":"string"},"how_to_run":{"type":"string"},"test_command":{"type":"string","minLength":1},"notes":{"type":"string"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('test_report', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/test_report/v1","title":"test_report","type":"object","required":["passed","failed","summary"],"properties":{"build_sha":{"type":"string"},"suite":{"type":"string"},"passed":{"type":"integer","minimum":0},"failed":{"type":"integer","minimum":0},"skipped":{"type":"integer","minimum":0},"failures":{"type":"array","items":{"type":"object","required":["name"],"properties":{"name":{"type":"string"},"message":{"type":"string"},"file":{"type":"string"}}}},"summary":{"type":"string","minLength":1}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('review', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/review/v1","title":"review","type":"object","required":["verdict","summary","findings"],"properties":{"verdict":{"type":"string","enum":["approve","request_changes"]},"summary":{"type":"string","minLength":1},"findings":{"type":"array","items":{"type":"object","required":["severity","note"],"properties":{"severity":{"type":"string","enum":["blocker","major","minor"]},"file":{"type":"string"},"line":{"type":"integer"},"note":{"type":"string"}}}}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('migration', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/migration/v1","title":"migration","type":"object","required":["name","path","reversible"],"properties":{"name":{"type":"string","minLength":1},"path":{"type":"string","minLength":1},"reversible":{"type":"boolean"},"summary":{"type":"string"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('pr', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/pr/v1","title":"pr","description":"Validated against the artefact''s meta (a PR has no content blob). Either a number (existing PR) or a branch (the service opens it) is required.","type":"object","required":["repo"],"properties":{"repo":{"type":"string","pattern":"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"},"number":{"type":"integer","minimum":1},"branch":{"type":"string"},"head_sha":{"type":"string"},"url":{"type":"string"},"title":{"type":"string"},"ci_status":{"type":"string","enum":["pending","success","failure"]},"merged":{"type":"boolean"}},"anyOf":[{"required":["number"]},{"required":["branch"]}],"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('db_schema', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/db_schema/v1","title":"db_schema","description":"Tables another role created or changed, so the consumer can code against them without reading the database.","type":"object","required":["tables"],"properties":{"engine":{"type":"string","description":"postgres, mysql, sqlite, mongodb, ..."},"schema":{"type":"string"},"connection_ref":{"type":"string","description":"Where the connection details live (env var name, secret name). Never the secret itself."},"migration_path":{"type":"string"},"tables":{"type":"array","minItems":1,"items":{"type":"object","required":["name","columns"],"properties":{"name":{"type":"string","minLength":1},"purpose":{"type":"string"},"primary_key":{"type":"array","items":{"type":"string"}},"columns":{"type":"array","minItems":1,"items":{"type":"object","required":["name","type"],"properties":{"name":{"type":"string","minLength":1},"type":{"type":"string","minLength":1},"nullable":{"type":"boolean"},"default":{"type":"string"},"references":{"type":"string"},"description":{"type":"string"}}}},"indexes":{"type":"array","items":{"type":"string"}}}}},"notes":{"type":"string"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('config', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/config/v1","title":"config","description":"A configuration file or set of keys another role produced, described so the consumer can rely on it.","type":"object","required":["path","keys"],"properties":{"path":{"type":"string","minLength":1,"description":"Where the file lives relative to the repository or system root."},"format":{"type":"string","enum":["json","yaml","toml","env","ini","other"]},"keys":{"type":"array","minItems":1,"items":{"type":"object","required":["name"],"properties":{"name":{"type":"string","minLength":1},"type":{"type":"string"},"default":{},"required":{"type":"boolean"},"description":{"type":"string"}}}},"how_to_load":{"type":"string"},"notes":{"type":"string"}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
insert into baton.artifact_schemas (kind, version, schema) values ('handoff', 'v1', '{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://clane.sh/baton/schemas/handoff/v1","title":"handoff","description":"The result of delegated work that fits no more specific kind: what was done, where, and what the consumer must know.","type":"object","required":["summary"],"properties":{"summary":{"type":"string","minLength":1},"details":{"type":"string"},"artifacts":{"type":"array","items":{"type":"object","required":["path"],"properties":{"path":{"type":"string"},"description":{"type":"string"}}}},"references":{"type":"array","items":{"type":"string"}},"how_to_use":{"type":"string"},"caveats":{"type":"array","items":{"type":"string"}}},"additionalProperties":true}'::jsonb)
  on conflict (kind, version) do update set schema = excluded.schema;
